# Generated by Django 5.2.7 on 2025-10-18 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImagemUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resultado', models.CharField(blank=True, max_length=255, null=True)),
                ('probabilidade', models.FloatField(blank=True, null=True)),
                ('enviado_em', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
